info:
  description: Spring Cloud Samples - For my personal configuration
  url: https://github.com/davisusanibar/netflixoss-all-tour-config
eureka:
  password: '{cipher}AQA49kaJxMYc2Aq1txPRk8LVzeFKLwWycX1RnDcOw9k4nyU7zqVSoSCIIS7ogFdMaonUkacAXv5xBixf3aqiu/cR+goz1M04E6NL1cZHMBk18v/6cTSXODBhVz8OT7rD2/R38xB27Yo9qYYWwArNHk4qjiCw4jg9e+sKRuyzkkneRPlycLZT4/FrbZLHaA9CRxwmjnIMMneTfuf0fsChjgORzO4X+WYD0lWI4xMo5pIHt8LjvFNthZumWDJO2EURvxTOOvS3YTtbg65p3yUHvD8O1Nukmz/mtzUVY5NVZfuCEu5p+wGv/ew0NX5sepZY/Fj+Bs9XKyHHBTLA5cZ5nzzm6GYOQ2moZ4dU6AjcebbLrWcyNdDRU7ORgpMoYT9Tfic='
  client:
    serviceUrl:
      defaultZone: http://adminusereureka:${eureka.password:}@localhost:8585/eureka/

---
spring:
  profiles: cloud
  cloud:
    config:
      uri: ${vcap.services.${PREFIX:}configserver.credentials.uri:http://user:password@${PREFIX:}configserver.${application.domain:cfapps.io}}
oauth2:
  client:
    tokenUri: ${vcap.services.${PREFIX:}sso.credentials.tokenUri:}
    authorizationUri: ${vcap.services.${PREFIX:}sso.credentials.authorizationUri:}
    clientId: ${vcap.services.${PREFIX:}sso.credentials.clientId:}
    clientSecret: ${vcap.services.${PREFIX:}sso.credentials.clientSecret:}
  resource:
    tokenInfoUri: ${vcap.services.${OAUTH2_RESOURCE_SERVICEID:${oauth2.resource.serviceId:sso}}.credentials.tokenInfoUri:}
    serviceId: ${PREFIX:}resource
application:
  domain: ${APPLICATION_DOMAIN:cfapps.io}
endpoints:
  restart: enabled
eureka:
  password: password
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    nonSecurePort: 80
  client:
    serviceUrl:
      defaultZone: ${vcap.services.${PREFIX:}eureka.credentials.uri:http://user:${eureka.password:}@${PREFIX:}eureka.${application.domain:cfapps.io}}/eureka/

---
spring:
  profiles: docker
  cloud:
    config:
      uri: http://${CONFIGSERVER_1_PORT_8888_TCP_ADDR:localhost}:8888
endpoints:
  restart: enabled
eureka:
  instance:
    nonSecurePort: 80
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_1_PORT_8761_TCP_ADDR:localhost}:8761/eureka/